[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile.backend"

[deploy]
  startCommand = "python backend/app.py"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[env]
  PORT = { default = "5000" }
  FLASK_ENV = { default = "production" }